/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3W4LrkxyvNb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"

export function homepage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="sticky top-0 z-40 w-full border-b bg-background">
        <div className="container flex h-16 items-center justify-between py-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <LifeBuoyIcon className="h-6 w-6" />
            <span className="font-bold">LIFE SYSTEM</span>
          </Link>
          <nav className="hidden md:flex md:gap-6">
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Blog
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              LIFE SYSTEM Journey
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <div />
            <Button variant="outline" size="sm" className="hidden md:inline-flex">
              Contact
            </Button>
            <Sheet>
              <SheetTrigger asChild>
                <Button variant="ghost" size="icon" className="md:hidden">
                  <MenuIcon className="h-6 w-6" />
                </Button>
              </SheetTrigger>
              <SheetContent side="right" className="w-full max-w-xs">
                <div className="grid gap-4 p-4">
                  <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
                    Home
                  </Link>
                  <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
                    Blog
                  </Link>
                  <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
                    Projects
                  </Link>
                  <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
                    LIFE SYSTEM Journey
                  </Link>
                  <Button variant="outline" size="sm">
                    Contact
                  </Button>
                </div>
              </SheetContent>
            </Sheet>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="container py-12 md:py-16 lg:py-20">
          <div className="grid gap-8 md:grid-cols-2 md:gap-12 lg:gap-16">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                Welcome to my LIFE SYSTEM Journey
              </h1>
              <p className="text-muted-foreground md:text-lg">
                Explore my personal website and learn about my LIFE SYSTEM journey, projects, and more.
              </p>
              <div className="flex gap-4">
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Learn More
                </Link>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Read Blog
                </Link>
              </div>
            </div>
            <div className="flex justify-center">
              <img
                src="/placeholder.svg"
                width={400}
                height={400}
                alt="LIFE SYSTEM Illustration"
                className="max-w-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }}
              />
            </div>
          </div>
        </section>
        <section className="container py-12 md:py-16 lg:py-20">
          <div className="grid gap-8 md:grid-cols-2 md:gap-12 lg:gap-16">
            <div>
              <h2 className="mb-4 text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Latest Blog Posts</h2>
              <div className="grid gap-6">
                <Card className="group">
                  <CardHeader>
                    <CardTitle>
                      <Link
                        href="#"
                        className="text-lg font-medium transition-colors group-hover:text-primary"
                        prefetch={false}
                      >
                        Unlocking the Power of LIFE SYSTEM
                      </Link>
                    </CardTitle>
                    <CardDescription className="text-muted-foreground">
                      Discover how LIFE SYSTEM can transform your life.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={225}
                      alt="Blog Post 1"
                      className="rounded-md object-cover"
                      style={{ aspectRatio: "400/225", objectFit: "cover" }}
                    />
                  </CardContent>
                </Card>
                <Card className="group">
                  <CardHeader>
                    <CardTitle>
                      <Link
                        href="#"
                        className="text-lg font-medium transition-colors group-hover:text-primary"
                        prefetch={false}
                      >
                        Mastering the Art of LIFE SYSTEM Journaling
                      </Link>
                    </CardTitle>
                    <CardDescription className="text-muted-foreground">
                      Learn how to use LIFE SYSTEM journaling to achieve your goals.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={225}
                      alt="Blog Post 2"
                      className="rounded-md object-cover"
                      style={{ aspectRatio: "400/225", objectFit: "cover" }}
                    />
                  </CardContent>
                </Card>
              </div>
            </div>
            <div>
              <h2 className="mb-4 text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Featured Projects</h2>
              <div className="grid gap-6">
                <Card className="group">
                  <CardHeader>
                    <CardTitle>
                      <Link
                        href="#"
                        className="text-lg font-medium transition-colors group-hover:text-primary"
                        prefetch={false}
                      >
                        LIFE SYSTEM Planner
                      </Link>
                    </CardTitle>
                    <CardDescription className="text-muted-foreground">
                      A comprehensive planner to help you achieve your LIFE SYSTEM goals.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={225}
                      alt="Project 1"
                      className="rounded-md object-cover"
                      style={{ aspectRatio: "400/225", objectFit: "cover" }}
                    />
                  </CardContent>
                </Card>
                <Card className="group">
                  <CardHeader>
                    <CardTitle>
                      <Link
                        href="#"
                        className="text-lg font-medium transition-colors group-hover:text-primary"
                        prefetch={false}
                      >
                        LIFE SYSTEM Habit Tracker
                      </Link>
                    </CardTitle>
                    <CardDescription className="text-muted-foreground">
                      A simple and effective tool to build and maintain LIFE SYSTEM habits.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <img
                      src="/placeholder.svg"
                      width={400}
                      height={225}
                      alt="Project 2"
                      className="rounded-md object-cover"
                      style={{ aspectRatio: "400/225", objectFit: "cover" }}
                    />
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t bg-background">
        <div className="container flex flex-col items-center justify-between gap-4 py-8 md:flex-row">
          <div className="flex items-center gap-4">
            <Link href="#" className="flex items-center gap-2" prefetch={false}>
              <LifeBuoyIcon className="h-6 w-6" />
              <span className="font-bold">LIFE SYSTEM</span>
            </Link>
            <div className="hidden md:block">
              <span className="text-muted-foreground">&copy; 2024 LIFE SYSTEM. All rights reserved.</span>
            </div>
          </div>
          <div className="flex gap-4">
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
              <TwitterIcon className="h-6 w-6" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
              <InstagramIcon className="h-6 w-6" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
              <LinkedinIcon className="h-6 w-6" />
            </Link>
          </div>
          <div className="block md:hidden">
            <span className="text-muted-foreground">&copy; 2024 LIFE SYSTEM. All rights reserved.</span>
          </div>
        </div>
      </footer>
    </div>
  )
}

function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LifeBuoyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m4.93 4.93 4.24 4.24" />
      <path d="m14.83 9.17 4.24-4.24" />
      <path d="m14.83 14.83 4.24 4.24" />
      <path d="m9.17 14.83-4.24 4.24" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
