/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sRJyJmbFwn1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export function Projects() {
  return (
    <div className="w-full max-w-6xl mx-auto py-8 px-4 md:px-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="rounded-full">
            <LayoutGridIcon className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="icon" className="rounded-full">
            <ListIcon className="w-5 h-5" />
          </Button>
        </div>
        <div className="relative flex-1 max-w-md">
          <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input type="search" placeholder="Search projects..." className="w-full rounded-lg bg-background pl-8" />
        </div>
        <div className="flex items-center gap-4">
          <Select defaultValue="all">
            <SelectTrigger className="w-40">
              <SelectValue placeholder="All LIFE SYSTEM" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All LIFE SYSTEM</SelectItem>
              <SelectItem value="v1">LIFE SYSTEM v1</SelectItem>
              <SelectItem value="v2">LIFE SYSTEM v2</SelectItem>
              <SelectItem value="v3">LIFE SYSTEM v3</SelectItem>
            </SelectContent>
          </Select>
          <Select defaultValue="all">
            <SelectTrigger className="w-40">
              <SelectValue placeholder="All Tags" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Tags</SelectItem>
              <SelectItem value="frontend">Frontend</SelectItem>
              <SelectItem value="backend">Backend</SelectItem>
              <SelectItem value="mobile">Mobile</SelectItem>
              <SelectItem value="devops">DevOps</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>shadcn/ui</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v2</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Beautifully designed components that you can copy and paste into your apps.
            </p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Frontend</Badge>
              <Badge variant="outline">React</Badge>
              <Badge variant="outline">Tailwind</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>vercel/next.js</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v3</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">The React Framework for Production.</p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Frontend</Badge>
              <Badge variant="outline">React</Badge>
              <Badge variant="outline">SSR</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>prisma/prisma</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v1</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">Prisma is a next-generation ORM that simplifies database access.</p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Backend</Badge>
              <Badge variant="outline">ORM</Badge>
              <Badge variant="outline">Database</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>tailwindlabs/tailwindcss</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v2</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">A utility-first CSS framework for rapidly building custom designs.</p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Frontend</Badge>
              <Badge variant="outline">CSS</Badge>
              <Badge variant="outline">Utility</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>remix-run/remix</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v3</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Remix is a full stack web framework that lets you focus on the user interface and work back through web
              standards to deliver a fast, slick, and resilient user experience.
            </p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Frontend</Badge>
              <Badge variant="outline">Backend</Badge>
              <Badge variant="outline">React</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <GithubIcon className="w-5 h-5" />
              <CardTitle>vercel/swr</CardTitle>
            </div>
            <Badge variant="outline">LIFE SYSTEM v1</Badge>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">React Hooks for Data Fetching.</p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="outline">Frontend</Badge>
              <Badge variant="outline">React</Badge>
              <Badge variant="outline">Data Fetching</Badge>
            </div>
          </CardContent>
          <CardFooter>
            <Link href="#" className="inline-flex items-center gap-2" prefetch={false}>
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </Link>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LayoutGridIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}
